"""Agrega columna precio a Libro

Revision ID: 16336fa00bfb
Revises: fdfab52555d8
Create Date: 2025-05-20 15:47:30.149760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16336fa00bfb'
down_revision = 'fdfab52555d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('libro', schema=None) as batch_op:
        batch_op.alter_column('portada',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('libro', schema=None) as batch_op:
        batch_op.alter_column('portada',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)

    # ### end Alembic commands ###
