"""Agrega campo portada a Libro

Revision ID: af5a60b6b156
Revises: 3bcbee81152c
Create Date: 2025-05-20 15:15:58.092154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af5a60b6b156'
down_revision = '3bcbee81152c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('libro', schema=None) as batch_op:
        batch_op.add_column(sa.Column('portada', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('libro', schema=None) as batch_op:
        batch_op.drop_column('portada')

    # ### end Alembic commands ###
