"""Agrega campo portada a Libro

Revision ID: fdfab52555d8
Revises: af5a60b6b156
Create Date: 2025-05-20 15:28:41.289276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdfab52555d8'
down_revision = 'af5a60b6b156'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('libro', schema=None) as batch_op:
        batch_op.add_column(sa.Column('precio', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('libro', schema=None) as batch_op:
        batch_op.drop_column('precio')

    # ### end Alembic commands ###
